using System;
using UnityEngine.XR.ARSubsystems;

namespace UnityEngine.XR.ARFoundation
{
    /// <summary>
    /// Represents a 3D bounding box detected by an AR device.
    /// </summary>
    /// <remarks>
    /// Generated by the <see cref="ARBoundingBoxManager"/> when an AR device detects
    /// a 3D bounding box in the environment.
    /// </remarks>
    [DisallowMultipleComponent]
    [HelpURL(typeof(ARBoundingBox))]
    public class ARBoundingBox : ARTrackable<XRBoundingBox, ARBoundingBox>
    {
        /// <summary>
        /// The physical size (dimensions) of the bounding box in meters.
        /// </summary>
        public Vector3 size => sessionRelativeData.size;

        /// <summary>
        /// The classifications of this bounding box.
        /// </summary>
        public BoundingBoxClassifications classifications => sessionRelativeData.classifications;
    }
}
