using System;
using UnityEngine.XR.ARSubsystems;

namespace UnityEngine.XR.ARFoundation
{
    /// <summary>
    /// Represents a participant (that is, another device in a collaborative session).
    /// </summary>
    /// <remarks>
    /// Generated by the <see cref="ARParticipantManager"/> to represent another participant in the session.
    /// </remarks>
    // [DefaultExecutionOrder(ARUpdateOrder.k_Plane)]
    [DisallowMultipleComponent]
    [HelpURL(typeof(ARParticipant))]
    public sealed class ARParticipant : ARTrackable<XRParticipant, ARParticipant>
    {
        /// <summary>
        /// Get this participant's session identifier.
        /// </summary>
        public Guid sessionId { get { return sessionRelativeData.sessionId; } }
    }
}
